# Generated by Django 2.1 on 2018-08-15 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marcador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcador', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('data_encerramento', models.DateField(blank=True, null=True)),
                ('tarefa_tempo_total', models.TimeField(blank=True, null=True)),
                ('arquivado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa_has_Marcador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Marcador')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Tarefa')),
            ],
        ),
        migrations.CreateModel(
            name='TarefaParcial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_tarefa', models.DateField(auto_now_add=True)),
                ('final_tarefa', models.DateField(blank=True, null=True)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Tarefa')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=25)),
                ('senha', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tarefa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Usuario'),
        ),
        migrations.AddField(
            model_name='marcador',
            name='tarefas',
            field=models.ManyToManyField(through='tasks.Tarefa_has_Marcador', to='tasks.Tarefa'),
        ),
    ]
